import ResetPassword from "../models/ResetPassword.js";
import config from "../config/config.js";
import User from "../models/User.js";
import bcrypt from "bcrypt";
import sendEmail from "../utils/email.js";

const login = async (data) => {
  const user = await User.findOne({
    $or: [{ email: data?.email }, { phone: data?.phone }],
  });

  //  console.log(user);

  if (!user) {
    throw {
      status: 404,
      message: "no user",
    };
  }

  const isPasswordMatch = bcrypt.compareSync(data.password, user.password);

  if (!isPasswordMatch) {
    throw {
      status: 400,
      message: "not match PW",
    };
  }

  return {
    _id: user._id,
    address: user.address,
    phone: user.phone,
    email: user.email,
    name: user.name,
    roles: user.roles,
    isActive: user.isActive,
    id: user._id,
  };
  //find user and match
};

const register = async (data) => {
  const user = await User.findOne({ email: data.email });

  if (user) {
    throw {
      status: 409,
      message: "invalid user",
    };
  }

  // salt generated by webpage from bcrypt!!
  const salt = bcrypt.genSaltSync(10);
  const hashedPassword = bcrypt.hashSync(data.password, salt);

  const createdUser = await User.create({
    ...data,
    password: hashedPassword,
  });

  return {
    _id: createdUser._id,
    address: createdUser.address,
    phone: createdUser.phone,
    email: createdUser.email,
    name: createdUser.name,
    roles: createdUser.roles,
    isActive: createdUser.isActive,
    id: createdUser._id,
  };
};

//reset password and forgot password!!
const forgotPassword = async (email) => {
  const user = await User.findOne({ email });

  if (!user) {
    throw {
      status: 404,
      message: "user not fund",
    };
  }

  const token = crypto.randomUUID();

  await ResetPassword.create({
    userId: user._id,
    token: token,
  });

  const link = `${config.appUrl}/reset-password?userId=${user._id}&token=${token}`;

  // const link = `${config.appUrl}/reset-password?id=${resetPassword._id}`;

  // send email with reset password link!!

  sendEmail({
    recipient: email,
    subject: "Reset password link",
    html: 
    `
      <div 
        style="
          padding: 25px; 
          font-family: sans-serif;
        "
      >
        <h1>plz reset the link to reset password</h1>
        <a 
          href="${link}" 
            style="
            background-color: rgb(87, 87, 85); 
            color: rgb(232, 255, 127); text-decoration:none;
            padding: 15px 20px;
            border-radius: 10px;
          "
        >reset password</a
      >
      </div>
    `,
  });

  return {
    message: "reset password link sent to your email.",
  };
};

const resetPassword = async (input) => {
  const data = await ResetPassword.findOne({
    userId: input.userId,
    expiredAt: { $gt: Date.now() },
  }).sort({ createdAt: -1 });

  if (!data || data.token != input.token) {
    throw {
      status: 400,
      message: "Invalid or expire link.",
    };
  }

  if (data.isUsed) {
    throw {
      status: 400,
      message: "link already used.",
    };
  }

  const salt = bcrypt.genSaltSync(10);
  const hashedPassword = bcrypt.hashSync(input.password, salt);

  await User.findByIdAndUpdate(input.userId, {
    password: hashedPassword,
  });

  await ResetPassword.findByIdAndUpdate(data._id, {
    isUsed: true,
  });

  return { message: "password reset successful." };
};

export default { register, login, forgotPassword, resetPassword };
